SELECT * FROM Employee
-- WHERE fname like 'ส%'
-- WHERE fname like '%ส%'
-- WHERE fname like '%ย'
-- WHERE fname like 'สม%'
-- WHERE fname like '%สม%'
-- WHERE fname like '%สม'
-- WHERE salary like '1%'
-- WHERE salary like '%1%'
-- WHERE salary like '%1'
-- WHERE salary like '500%'
-- WHERE salary like '%500%'
-- WHERE salary like '%500%'
-- WHERE salary like '%500%'
WHERE salary like '2%0'